version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.20
    container_name: mysql_container
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306" 
    volumes:
      - dbdata:/var/lib/mysql 
      - ./db/testdump.sql:/docker-entrypoint-initdb.d/testdump.sql  
    networks:     
      - linknet  
    restart: unless-stopped   
  
  web:
    build: ./api
    container_name: node_server_container
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysqldb 
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mysqldb  
    networks:     
      - linknet  
    restart: on-failure


networks:
  linknet:

volumes:
   dbdata: